# Generated by Django 3.1.7 on 2021-03-09 22:18

import datetime
from django.db import migrations, models
import taskmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0002_auto_20210310_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duedate',
            field=models.DateField(default=datetime.date.today, validators=[taskmanager.models.check_date], verbose_name='DueDate'),
        ),
    ]
